In [1]:
#imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
#allows plots to appear directly in the notebook
%matplotlib inline

In [3]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [94]:
#upload data
df = pd.read_csv(r"C:\Users\Sierra\Documents\heart-disease.csv")

In [95]:
#examine variables
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
age         303 non-null int64
sex         303 non-null int64
cp          303 non-null int64
trestbps    303 non-null int64
chol        303 non-null int64
fbs         303 non-null int64
restecg     303 non-null int64
thalach     303 non-null int64
exang       303 non-null int64
oldpeak     303 non-null float64
slope       303 non-null int64
ca          303 non-null int64
thal        303 non-null int64
target      303 non-null int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [96]:
#examine first few rows
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1        0      150      0      2.3      0   0     1       1
1   37    1   2       130   250    0        1      187      0      3.5      0   0     2       1
2   41    0   1       130   204    0        0      172      0      1.4      2   0     2       1
3   56    1   1       120   236    0        1      178      0      0.8      2   0     2       1
4   57    0   0       120   354    0        1      163      1      0.6      2   0     2       1

In [97]:
#examine descriptive statistics
df.describe()

age         sex          cp    trestbps        chol         fbs     restecg     thalach       exang     oldpeak       slope          ca        thal      target
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515    0.528053  149.646865    0.326733    1.039604    1.399340    0.729373    2.313531    0.544554
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198    0.525860   22.905161    0.469794    1.161075    0.616226    1.022606    0.612277    0.498835
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000    0.000000   71.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000    0.000000  133.500000    0.000000    0.000000    1.000000    0.000000    2.000000    0.000000
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000    1.000000  153.000000    0.000000    0.800000    1.000000    0.000000    2.000000    1.000000
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000    1.000000  166.000000    1.000000    1.600000    2.000000    1.000000    3.000000    1.000000
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000    2.000000  202.000000    1.000000    6.200000    2.000000    4.000000    3.000000    1.000000

In [98]:
#percent count of null values
df.isnull().sum()/len(df)*100

age         0.0
sex         0.0
cp          0.0
trestbps    0.0
chol        0.0
fbs         0.0
restecg     0.0
thalach     0.0
exang       0.0
oldpeak     0.0
slope       0.0
ca          0.0
thal        0.0
target      0.0
dtype: float64

In [99]:
#create dummy variables for cp
cp = pd.get_dummies(df['cp'],drop_first=True)

In [100]:
#print first few rows of cp
cp.head()

1  2  3
0  0  0  1
1  0  1  0
2  1  0  0
3  1  0  0
4  0  0  0

In [101]:
#create dummy variables for restecg
restecg = pd.get_dummies(df['restecg'],drop_first=True)

In [102]:
#print first few rows of restecg
restecg.head()

1  2
0  0  0
1  1  0
2  0  0
3  1  0
4  1  0

In [103]:
#create dummy variables for slope
slope = pd.get_dummies(df['slope'],drop_first=True)

In [104]:
#print first few rows of slope
slope.head()

1  2
0  0  0
1  0  0
2  0  1
3  0  1
4  0  1

In [105]:
#create dummy variables for ca
ca = pd.get_dummies(df['ca'],drop_first=True)

In [106]:
#print first few rows of ca
ca.head()

1  2  3  4
0  0  0  0  0
1  0  0  0  0
2  0  0  0  0
3  0  0  0  0
4  0  0  0  0

In [107]:
#create dummy variables for thal
thal = pd.get_dummies(df['thal'],drop_first=True)

In [108]:
#print first few rows of thal
thal.head()

1  2  3
0  1  0  0
1  0  1  0
2  0  1  0
3  0  1  0
4  0  1  0

In [109]:
#drop original variables for the dataset
df.drop(['cp','restecg','slope','ca','thal'], inplace = True, axis = 1)

In [110]:
#check for correlative relationships among numeric variables
df.corr()

age       sex  trestbps      chol       fbs   thalach     exang   oldpeak    target
age       1.000000 -0.098447  0.279351  0.213678  0.121308 -0.398522  0.096801  0.210013 -0.225439
sex      -0.098447  1.000000 -0.056769 -0.197912  0.045032 -0.044020  0.141664  0.096093 -0.280937
trestbps  0.279351 -0.056769  1.000000  0.123174  0.177531 -0.046698  0.067616  0.193216 -0.144931
chol      0.213678 -0.197912  0.123174  1.000000  0.013294 -0.009940  0.067023  0.053952 -0.085239
fbs       0.121308  0.045032  0.177531  0.013294  1.000000 -0.008567  0.025665  0.005747 -0.028046
thalach  -0.398522 -0.044020 -0.046698 -0.009940 -0.008567  1.000000 -0.378812 -0.344187  0.421741
exang     0.096801  0.141664  0.067616  0.067023  0.025665 -0.378812  1.000000  0.288223 -0.436757
oldpeak   0.210013  0.096093  0.193216  0.053952  0.005747 -0.344187  0.288223  1.000000 -0.430696
target   -0.225439 -0.280937 -0.144931 -0.085239 -0.028046  0.421741 -0.436757 -0.430696  1.000000

In [111]:
#concatenate dummies to dataframe
df = pd.concat([df,cp,restecg,slope,ca,thal],axis=1)

In [ ]:
#logistic regression model

In [112]:
#independent variables
X = df.drop('target',axis=1)

In [113]:
#dependent variable
y = df['target']

In [114]:
#import
from sklearn.model_selection import train_test_split

In [115]:
#train/test split of the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [116]:
#import
from sklearn.linear_model import LogisticRegression

In [117]:
#logit model
logmodel = LogisticRegression()

In [118]:
#model fit
logmodel.fit(X_train,y_train)

C:\Users\Sierra\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [119]:
#call predictions
predictions=logmodel.predict(X_test)

In [120]:
#import
from sklearn.metrics import classification_report

In [121]:
#classification report
print (classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.88      0.80      0.83        44
           1       0.82      0.89      0.86        47

    accuracy                           0.85        91
   macro avg       0.85      0.84      0.85        91
weighted avg       0.85      0.85      0.85        91



In [122]:
#compare distribution in data set to accuracy - looks good
df['target'].value_counts(normalize=True) * 100

1    54.455446
0    45.544554
Name: target, dtype: float64

In [123]:
#import
from sklearn.metrics import confusion_matrix

In [124]:
#print confusio matrix - looks good
confusion_matrix (y_test,predictions)

array([[35,  9],
       [ 5, 42]], dtype=int64)

In [ ]:
#decision tree model

In [125]:
#import
from sklearn.tree import DecisionTreeClassifier

In [126]:
#decision tree
dtree = DecisionTreeClassifier()

In [127]:
#model fit
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [128]:
#call predictions
predictions = dtree.predict(X_test)

In [130]:
#import
from sklearn.metrics import classification_report, confusion_matrix

In [131]:
#print classification report
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.67      0.68      0.67        44
           1       0.70      0.68      0.69        47

    accuracy                           0.68        91
   macro avg       0.68      0.68      0.68        91
weighted avg       0.68      0.68      0.68        91



In [132]:
#print confusion matrix
print(confusion_matrix(y_test,predictions))

[[30 14]
 [15 32]]


In [ ]:
#random forest model

In [133]:
#import
from sklearn.ensemble import RandomForestClassifier

In [134]:
#random forest model
rfc = RandomForestClassifier(n_estimators=300)

In [135]:
#model fit
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [136]:
#call predictions
predictions = rfc.predict(X_test)

In [137]:
#print classification report
#notice an improvement compared to decesion tree model
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.81      0.77      0.79        44
           1       0.80      0.83      0.81        47

    accuracy                           0.80        91
   macro avg       0.80      0.80      0.80        91
weighted avg       0.80      0.80      0.80        91



In [138]:
#print confusion matrix
print(confusion_matrix(y_test,predictions))

[[34 10]
 [ 8 39]]


In [ ]:
#conclusion : logit model outperforms both models
#random forest improves decision tree model
#in terms of precision, recall, f1-score, and accuracy